# Generated by Django 5.1.6 on 2026-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp_create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
