# Generated by Django 5.1.6 on 2026-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_otp_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
