openapi: 3.0.3
info:
  title: My E-Commerce API
  version: 1.0.0
  description: E-Commerce docs
paths:
  /api/category-list/:
    get:
      operationId: category_list_retrieve
      tags:
      - category-list
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: category_list_create
      tags:
      - category-list
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/create-user-profile/:
    get:
      operationId: create_user_profile_retrieve
      description: this endpoint for user profile
      summary: user profile
      tags:
      - create-user-profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    post:
      operationId: create_user_profile_create
      description: this endpoint for user profile
      summary: user profile
      tags:
      - create-user-profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    put:
      operationId: create_user_profile_update
      description: this endpoint for user profile
      summary: user profile
      tags:
      - create-user-profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    delete:
      operationId: create_user_profile_destroy
      description: this endpoint for user profile
      summary: user profile
      tags:
      - create-user-profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
  /api/register/:
    post:
      operationId: register_create
      description: user registration api
      summary: user registeration
      tags:
      - register
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSerilizer'
          description: ''
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPairRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/token/verify/:
    post:
      operationId: token_verify_create
      description: |-
        Takes a token and indicates if it is valid.  This view provides no
        information about a token's fitness for a particular use.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerifyRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenVerifyRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenVerifyRequest'
        required: true
      responses:
        '200':
          description: No response body
  /api/user-address/:
    get:
      operationId: user_address_retrieve
      description: this endpoint for user profile
      summary: user address
      tags:
      - user-address
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAddress'
          description: ''
    post:
      operationId: user_address_create
      description: this endpoint for user profile
      summary: user address
      tags:
      - user-address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAddressRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAddressRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserAddressRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAddress'
          description: ''
  /api/user-address-detail/{id}/:
    get:
      operationId: user_address_detail_retrieve
      description: this endpoint for user profile
      summary: user address
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user-address-detail
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAddress'
          description: ''
    put:
      operationId: user_address_detail_update
      description: this endpoint for user profile
      summary: user address
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user-address-detail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAddressRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAddressRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserAddressRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAddress'
          description: ''
    delete:
      operationId: user_address_detail_destroy
      description: this endpoint for user profile
      summary: user address
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user-address-detail
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAddress'
          description: ''
  /api/user-profile/:
    get:
      operationId: user_profile_retrieve
      description: this endpoint for user profile
      summary: user profile
      tags:
      - user-profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    post:
      operationId: user_profile_create
      description: this endpoint for user profile
      summary: user profile
      tags:
      - user-profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    put:
      operationId: user_profile_update
      description: this endpoint for user profile
      summary: user profile
      tags:
      - user-profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    delete:
      operationId: user_profile_destroy
      description: this endpoint for user profile
      summary: user profile
      tags:
      - user-profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
  /api/verify/:
    post:
      operationId: verify_create
      description: 'this endpoint for send otp for login user with jwt token '
      summary: verify user
      tags:
      - verify
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSerilizer'
          description: ''
components:
  schemas:
    RegisterSerilizer:
      type: object
      properties:
        mobile:
          type: string
          maxLength: 11
        otp:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
          nullable: true
      required:
      - mobile
    TokenObtainPair:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - refresh
    TokenObtainPairRequest:
      type: object
      properties:
        mobile:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - mobile
      - password
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
      required:
      - access
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - refresh
    TokenVerifyRequest:
      type: object
      properties:
        token:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - token
    UserAddress:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          readOnly: true
        street:
          type: string
          maxLength: 255
        city:
          type: string
          maxLength: 100
        state:
          type: string
          maxLength: 100
        postal_code:
          type: string
          maxLength: 20
        is_default:
          type: boolean
        user_profile:
          type: integer
          readOnly: true
      required:
      - city
      - id
      - postal_code
      - state
      - street
      - updated_at
      - user_profile
    UserAddressRequest:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        street:
          type: string
          minLength: 1
          maxLength: 255
        city:
          type: string
          minLength: 1
          maxLength: 100
        state:
          type: string
          minLength: 1
          maxLength: 100
        postal_code:
          type: string
          minLength: 1
          maxLength: 20
        is_default:
          type: boolean
      required:
      - city
      - postal_code
      - state
      - street
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          readOnly: true
        full_name:
          type: string
          nullable: true
          maxLength: 15
        user:
          type: integer
          readOnly: true
      required:
      - id
      - updated_at
      - user
    UserProfileRequest:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        full_name:
          type: string
          nullable: true
          maxLength: 15
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
